from django.db import models

class salleForm(models.Model):
    nom = models.CharField(max_length=100, label='Nom')
    etablissement = models.CharField(max_length=100, label='Etablissement')
    date_arrivee = models.DateField(label='Date au')
    date_depart = models.DateField(label='Date du')
    nom_salle_souhaite = models.CharField(max_length=100, label='Nom de la salle souhaite')
    nombre_personnes = models.IntegerField(label='Nombre de personnes')
    type_evenement = models.CharField(max_length=100, label='Type d\'evenement')
    pause_cafe = models.IntegerField(label='Pause café')
    dejeuner = models.IntegerField(label='Dejeuner')
    diner = models.IntegerField(label='Diner')
    nombre_courrier = models.IntegerField(label='Nombre de courrier')
    Moyen = models.CharField(max_length=100, label='Moyen')
    statue = models.CharField(max_length=100, label='Statue')
    commentaire = models.CharField(widget=models.Textarea, required=False, label='Commentaire')

class hebergementForm(models.Model):
    nombre_courrier = models.IntegerField(label='Nombre de courrier')
    etablissement = models.CharField(max_length=100, label='Etablissement')
    demandeur = models.CharField(max_length=100, label='Demandeur')
    capacité = models.IntegerField(label='Capacité')
    date_arrivee = models.DateField(label='Date au')
    date_depart = models.DateField(label='Date du')
    chambre_disponible = models.CharField(max_length=100, label='Chambre disponible')
    prise_charge = models.CharField(max_length=100, label='Prise en charge')
    nombre_personnes = models.IntegerField(label='Nombre de personnes')
    Moyen = models.sCharField(max_length=100, label='Moyen')
    statue = models.CharField(max_length=100, label='Statue')
    type = models.CharField(widget=models.Textarea, required=False, label='Type')
    
class salle_heberForm(models.Form):
    nom = models.CharField(max_length=100, label='Nom')
    etablissement = models.CharField(max_length=100, label='Etablissement')
    date_arrivee = models.DateField(label='Date au')
    date_depart = models.DateField(label='Date du')
    nom_salle_souhaite = models.CharField(max_length=100, label='Nom de la salle souhaite')
    nombre_personnes = models.IntegerField(label='Nombre de personnes')
    type_evenement = models.CharField(max_length=100, label='Type d\'evenement')
    pause_cafe = models.IntegerField(label='Pause café')
    dejeuner = models.IntegerField(label='Dejeuner')
    diner = models.IntegerField(label='Diner')
    nombre_courrier = models.IntegerField(label='Nombre de courrier')
    Moyen = models.CharField(max_length=100, label='Moyen')
    statue = models.CharField(max_length=100, label='Statue')
    commentaire = models.CharField(widget=models.Textarea, required=False, label='Commentaire')
    nombre_courrier = models.IntegerField(label='Nombre de courrier')
    etablissement = models.CharField(max_length=100, label='Etablissement')
    demandeur = models.CharField(max_length=100, label='Demandeur')
    capacité = models.IntegerField(label='Capacité')
    date_arrivee = models.DateField(label='Date au')
    date_depart = models.DateField(label='Date du')
    chambre_disponible = models.CharField(max_length=100, label='Chambre disponible')
    prise_charge = models.CharField(max_length=100, label='Prise en charge')
    nombre_personnes = models.IntegerField(label='Nombre de personnes')
    Moyen = models.CharField(max_length=100, label='Moyen')
    statue = models.CharField(max_length=100, label='Statue')
    type = models.CharField(widget=models.Textarea, required=False, label='Type')

#class Event(models.Model):
 #   title = models.CharField(max_length=100)
 #   start_time = models.DateTimeField()
  #  end_time = models.DateTimeField()